on:
  push:
    branches:
      - main
  workflow_dispatch:


permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          config-file: ".github/workflows/release-please-config.json"
          manifest-file: ".github/workflows/.release-please-manifest.json"
